name: camcode
description: A camera barcode scanner for Flutter Web
version: 1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.camcode
        pluginClass: CamcodePlugin
      ios:
        pluginClass: CamcodePlugin
      web:
        pluginClass: CamcodeWeb
        fileName: camcode_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"